### ISSUE TITLE
Not working on Gboard

### ISSUE THREAD

**Issue by AbsolutUser** [Mino260806/KeyboardGPT#41]
Already followed all the step but still not working.

My device
- Android 10 (Nusantara Project)
- SukiSU Ultra Root Method
- Latest Gboard Beta version 15.7.5.787916401-beta-arm64-v8a

Module
- Rezygisk 1.0.0-rc3
- Lsposed 1.10.2 JingMatrix

Idk this log will useful or not
[LSPosed_2025-08-17T16_06_05.078.zip](https://github.com/user-attachments/files/21821368/LSPosed_2025-08-17T16_06_05.078.zip)

**Comment by Mino260806** [comment]
Thanks for sharing logs. Here's the exception for reference

```
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/inputmethod/InlineSuggestionsRequest;
	at java.lang.reflect.Executable.getMethodReturnTypeInternal(Native Method)
	at java.lang.reflect.Method.getReturnType(Method.java:148)
	at java.lang.Class.getDeclaredMethods(Class.java:1883)
	at JQBBgwxewiSQ.ZfzeJbusQ.XposedHelpers.lambda$findMethodBestMatch$4(Unknown Source:7)
	at JQBBgwxewiSQ.ZfzeJbusQ.XposedHelpers.f(Unknown Source:0)
	at JQBBgwxewiSQ.ZfzeJbusQ.a.apply(Unknown Source:21)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1716)
	at JQBBgwxewiSQ.ZfzeJbusQ.XposedHelpers.findMethodBestMatch(SourceFile:3)
	at tn.amin.keyboard_gpt.hook.HookManager.hook(HookManager.java:18)
	at tn.amin.keyboard_gpt.MainHook.hookMethodService(MainHook.java:103)
	at tn.amin.keyboard_gpt.MainHook.access$100(MainHook.java:22)
	at tn.amin.keyboard_gpt.MainHook$1.afterHookedMethod(MainHook.java:72)
	at JQBBgwxewiSQ.ZfzeJbusQ.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at org.lsposed.lspd.impl.LSPosedBridge$NativeHooker.callback(Unknown Source:281)
	at LSPHooker_.onCreate(Unknown Source:8)
	at wqc.onCreate(PG:40)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3953)
	at android.app.ActivityThread.access$1500(ActivityThread.java:219)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1875)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)<
```


Apparently, the module tries to find a class (`Landroid/view/inputmethod/InlineSuggestionsRequest;`) that's only present on Android 11 and upwards. This is a bug in LSPosed API itself. I don't know if it's specific to JingMatrix fork, but I'll find try to find a workaround, by reimplementing the underlying API myself.
Stay tuned, I'll attach soon an apk for you to test it and report back.

**Comment by Mino260806** [comment]
@AbsolutUser this should fix this issue. Please try it and let me know if works, so I can include it in next release. 

[KeyboardGPT-release-v2.0.1-dev.zip](https://github.com/user-attachments/files/21829032/KeyboardGPT-release-v2.0.1-dev.zip)
(Rename extension to .apk before installing)

**Comment by AbsolutUser** [comment]
@Mino260806 still not working

What I do
- Uninstall the old version
- do some cleaning with sdmaid (maybe there still some junk)
- reboot
- install the app and activated on lsposed
- force close Gboard and try but NOT WORK
- reboot
- try again,still NOT WORK
- force close Gboard and try again, still NOT WORK


Here's the log : 
[LSPosed_2025-08-18T14_37_45.050.zip](https://github.com/user-attachments/files/21829787/LSPosed_2025-08-18T14_37_45.050.zip)

**Comment by Mino260806** [comment]
@AbsolutUser oops, I forgot a detail that made the error still occur. I hope it works now. Waiting for your confirmation

[KeyboardGPT-release-v2.0.1-dev.zip](https://github.com/user-attachments/files/21830166/KeyboardGPT-release-v2.0.1-dev.zip)

**Comment by AbsolutUser** [comment]
@Mino260806 thanks now it works perfectly.
I tried on different app and it's like not all app can trigger the keyboardGPT popup like zarchiver text editor

But anyway thanks for your hard works😁

Idk this log still needed or not but just in case if you need it
[LSPosed_2025-08-18T15_39_16.462.zip](https://github.com/user-attachments/files/21830900/LSPosed_2025-08-18T15_39_16.462.zip)

**Comment by Mino260806** [comment]
> I tried on different app and it's like not all app can trigger the keyboardGPT popup like zarchiver text editor

I haven't found an app yet in which it doesn't work, so that's a valuable observation. Please consider opening another issue with the details (and examples) if you want to help me fix it
